# Generated by Django 4.2.13 on 2026-05-16 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('AdminID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'ADMIN',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('CartID', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'CART',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryType', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateTimeField(auto_now_add=True)),
                ('OrderAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DiscountAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('QuantitySold', models.IntegerField()),
                ('PaymentType', models.CharField(max_length=50)),
                ('OrderStatus', models.CharField(choices=[('To Pay', 'To Pay'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='To Pay', max_length=20)),
                ('DeliveryAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('PickupLocation', models.CharField(blank=True, max_length=100, null=True)),
                ('PickupDate', models.DateField(blank=True, null=True)),
                ('PickupTimeSlot', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ORDER',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(blank=True, max_length=50, null=True)),
                ('LastName', models.CharField(blank=True, max_length=50, null=True)),
                ('Username', models.CharField(max_length=15, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('ContactNum', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=100)),
                ('Barangay', models.CharField(blank=True, default='', max_length=100)),
                ('Municipality', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'USER',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('VoucherID', models.AutoField(primary_key=True, serialize=False)),
                ('VoucherCode', models.CharField(max_length=50, unique=True)),
                ('DiscountType', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=10)),
                ('DiscountValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MinPurchase', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('UsageLimit', models.IntegerField(default=1)),
                ('UsedCount', models.IntegerField(default=0)),
                ('IsActive', models.BooleanField(default=True)),
                ('PaymentMethodCondition', models.CharField(choices=[('both', 'Both (COD & Pickup)'), ('cod', 'Cash on Delivery Only'), ('pickup', 'Cash on Pickup Only')], default='both', max_length=10)),
                ('MaxDiscount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('FirstPurchaseOnly', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'VOUCHER',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductDescription', models.TextField(blank=True, null=True)),
                ('StockQuantity', models.IntegerField(default=0)),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ProductImage', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('Category', models.ForeignKey(db_column='CategoryID', on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
            options={
                'db_table': 'PRODUCT',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('OrderItemID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductQuantity', models.IntegerField()),
                ('UnitPrice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Order', models.ForeignKey(db_column='OrderID', on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('Product', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'db_table': 'ORDER_ITEM',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='User',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='order',
            name='Voucher',
            field=models.ForeignKey(blank=True, db_column='VoucherID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.voucher'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('CartItemID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductQuantity', models.IntegerField(default=1)),
                ('Cart', models.ForeignKey(db_column='CartID', on_delete=django.db.models.deletion.CASCADE, to='api.cart')),
                ('Product', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'db_table': 'CART_ITEM',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='User',
            field=models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('Action', models.CharField(max_length=255)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Admin', models.ForeignKey(db_column='AdminID', on_delete=django.db.models.deletion.CASCADE, to='api.admin')),
            ],
            options={
                'db_table': 'ADMIN_LOG',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('FavoriteID', models.AutoField(primary_key=True, serialize=False)),
                ('Product', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('User', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'FAVORITES',
                'unique_together': {('User', 'Product')},
            },
        ),
    ]
